// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: chord.proto

package protogen

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node represents a node in the Chord ring.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node ID as a byte array (160 bits / 20 bytes)
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Network host (IP address or hostname)
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// Network port
	Port          int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_chord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Node) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// FindSuccessorRequest asks a node to find the successor of a given ID.
type FindSuccessorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID to find the successor for
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRequest) Reset() {
	*x = FindSuccessorRequest{}
	mi := &file_chord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRequest) ProtoMessage() {}

func (x *FindSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{1}
}

func (x *FindSuccessorRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// FindSuccessorResponse contains the successor node.
type FindSuccessorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The successor node
	Successor     *Node `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorResponse) Reset() {
	*x = FindSuccessorResponse{}
	mi := &file_chord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorResponse) ProtoMessage() {}

func (x *FindSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorResponse.ProtoReflect.Descriptor instead.
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{2}
}

func (x *FindSuccessorResponse) GetSuccessor() *Node {
	if x != nil {
		return x.Successor
	}
	return nil
}

// GetPredecessorRequest asks a node for its predecessor.
type GetPredecessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorRequest) Reset() {
	*x = GetPredecessorRequest{}
	mi := &file_chord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorRequest) ProtoMessage() {}

func (x *GetPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorRequest.ProtoReflect.Descriptor instead.
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{3}
}

// GetPredecessorResponse contains the predecessor node.
type GetPredecessorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The predecessor node (may be nil if not set)
	Predecessor   *Node `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorResponse) Reset() {
	*x = GetPredecessorResponse{}
	mi := &file_chord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorResponse) ProtoMessage() {}

func (x *GetPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorResponse.ProtoReflect.Descriptor instead.
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{4}
}

func (x *GetPredecessorResponse) GetPredecessor() *Node {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

// NotifyRequest notifies a node that another node might be its predecessor.
type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node that might be the predecessor
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_chord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// NotifyResponse acknowledges the notification.
type NotifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_chord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetSuccessorListRequest asks a node for its successor list.
type GetSuccessorListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorListRequest) Reset() {
	*x = GetSuccessorListRequest{}
	mi := &file_chord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListRequest) ProtoMessage() {}

func (x *GetSuccessorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListRequest.ProtoReflect.Descriptor instead.
func (*GetSuccessorListRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{7}
}

// GetSuccessorListResponse contains the successor list.
type GetSuccessorListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of successor nodes
	Successors    []*Node `protobuf:"bytes,1,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorListResponse) Reset() {
	*x = GetSuccessorListResponse{}
	mi := &file_chord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListResponse) ProtoMessage() {}

func (x *GetSuccessorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListResponse.ProtoReflect.Descriptor instead.
func (*GetSuccessorListResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{8}
}

func (x *GetSuccessorListResponse) GetSuccessors() []*Node {
	if x != nil {
		return x.Successors
	}
	return nil
}

// PingRequest is used for health checks.
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_chord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PingResponse acknowledges the ping.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp of the response
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_chord_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetNodeInfoRequest asks for the node's information.
type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_chord_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{11}
}

// GetNodeInfoResponse contains the node's information.
type GetNodeInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's information
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_chord_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{12}
}

func (x *GetNodeInfoResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// GetRequest retrieves a value by key from the DHT.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to retrieve
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_chord_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{13}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse contains the retrieved value.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value (empty if not found)
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Whether the key was found
	Found         bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_chord_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{14}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// SetRequest stores a key-value pair in the DHT.
type SetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to store
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value to store
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// TTL in seconds (0 = no expiration)
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_chord_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{15}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// SetResponse acknowledges the set operation.
type SetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_chord_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{16}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeleteRequest removes a key from the DHT.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to delete
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_chord_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteResponse acknowledges the delete operation.
type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_chord_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ClosestPrecedingFingerRequest asks for the closest preceding finger.
type ClosestPrecedingFingerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID to find the closest preceding finger for
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosestPrecedingFingerRequest) Reset() {
	*x = ClosestPrecedingFingerRequest{}
	mi := &file_chord_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosestPrecedingFingerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosestPrecedingFingerRequest) ProtoMessage() {}

func (x *ClosestPrecedingFingerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosestPrecedingFingerRequest.ProtoReflect.Descriptor instead.
func (*ClosestPrecedingFingerRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{19}
}

func (x *ClosestPrecedingFingerRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// ClosestPrecedingFingerResponse contains the closest preceding node.
type ClosestPrecedingFingerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The closest preceding node
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosestPrecedingFingerResponse) Reset() {
	*x = ClosestPrecedingFingerResponse{}
	mi := &file_chord_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosestPrecedingFingerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosestPrecedingFingerResponse) ProtoMessage() {}

func (x *ClosestPrecedingFingerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosestPrecedingFingerResponse.ProtoReflect.Descriptor instead.
func (*ClosestPrecedingFingerResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{20}
}

func (x *ClosestPrecedingFingerResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// TransferKeysRequest asks a node to transfer keys in a range.
type TransferKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the range (exclusive)
	StartId []byte `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	// End of the range (inclusive)
	EndId         []byte `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferKeysRequest) Reset() {
	*x = TransferKeysRequest{}
	mi := &file_chord_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferKeysRequest) ProtoMessage() {}

func (x *TransferKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferKeysRequest.ProtoReflect.Descriptor instead.
func (*TransferKeysRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{21}
}

func (x *TransferKeysRequest) GetStartId() []byte {
	if x != nil {
		return x.StartId
	}
	return nil
}

func (x *TransferKeysRequest) GetEndId() []byte {
	if x != nil {
		return x.EndId
	}
	return nil
}

// KeyValuePair represents a single key-value pair.
type KeyValuePair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// TTL remaining in seconds (0 = no expiration)
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_chord_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{22}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValuePair) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// TransferKeysResponse contains the keys in the requested range.
type TransferKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of key-value pairs
	Keys []*KeyValuePair `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Number of keys transferred
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferKeysResponse) Reset() {
	*x = TransferKeysResponse{}
	mi := &file_chord_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferKeysResponse) ProtoMessage() {}

func (x *TransferKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferKeysResponse.ProtoReflect.Descriptor instead.
func (*TransferKeysResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{23}
}

func (x *TransferKeysResponse) GetKeys() []*KeyValuePair {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TransferKeysResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// DeleteTransferredKeysRequest asks a node to delete keys in a range.
type DeleteTransferredKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the range (exclusive)
	StartId []byte `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	// End of the range (inclusive)
	EndId         []byte `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferredKeysRequest) Reset() {
	*x = DeleteTransferredKeysRequest{}
	mi := &file_chord_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferredKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferredKeysRequest) ProtoMessage() {}

func (x *DeleteTransferredKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferredKeysRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransferredKeysRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteTransferredKeysRequest) GetStartId() []byte {
	if x != nil {
		return x.StartId
	}
	return nil
}

func (x *DeleteTransferredKeysRequest) GetEndId() []byte {
	if x != nil {
		return x.EndId
	}
	return nil
}

// DeleteTransferredKeysResponse confirms deletion.
type DeleteTransferredKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether deletion was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of keys deleted
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferredKeysResponse) Reset() {
	*x = DeleteTransferredKeysResponse{}
	mi := &file_chord_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferredKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferredKeysResponse) ProtoMessage() {}

func (x *DeleteTransferredKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferredKeysResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransferredKeysResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteTransferredKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTransferredKeysResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_chord_proto protoreflect.FileDescriptor

const file_chord_proto_rawDesc = "" +
	"\n" +
	"\vchord.proto\x12\bprotogen\x1a\x1cgoogle/api/annotations.proto\">\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"&\n" +
	"\x14FindSuccessorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"E\n" +
	"\x15FindSuccessorResponse\x12,\n" +
	"\tsuccessor\x18\x01 \x01(\v2\x0e.protogen.NodeR\tsuccessor\"\x17\n" +
	"\x15GetPredecessorRequest\"J\n" +
	"\x16GetPredecessorResponse\x120\n" +
	"\vpredecessor\x18\x01 \x01(\v2\x0e.protogen.NodeR\vpredecessor\"3\n" +
	"\rNotifyRequest\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.protogen.NodeR\x04node\"*\n" +
	"\x0eNotifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x19\n" +
	"\x17GetSuccessorListRequest\"J\n" +
	"\x18GetSuccessorListResponse\x12.\n" +
	"\n" +
	"successors\x18\x01 \x03(\v2\x0e.protogen.NodeR\n" +
	"successors\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x14\n" +
	"\x12GetNodeInfoRequest\"9\n" +
	"\x13GetNodeInfoResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.protogen.NodeR\x04node\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"U\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x1dClosestPrecedingFingerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"D\n" +
	"\x1eClosestPrecedingFingerResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.protogen.NodeR\x04node\"G\n" +
	"\x13TransferKeysRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\fR\astartId\x12\x15\n" +
	"\x06end_id\x18\x02 \x01(\fR\x05endId\"W\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"X\n" +
	"\x14TransferKeysResponse\x12*\n" +
	"\x04keys\x18\x01 \x03(\v2\x16.protogen.KeyValuePairR\x04keys\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"P\n" +
	"\x1cDeleteTransferredKeysRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\fR\astartId\x12\x15\n" +
	"\x06end_id\x18\x02 \x01(\fR\x05endId\"O\n" +
	"\x1dDeleteTransferredKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xb1\b\n" +
	"\fChordService\x12P\n" +
	"\rFindSuccessor\x12\x1e.protogen.FindSuccessorRequest\x1a\x1f.protogen.FindSuccessorResponse\x12S\n" +
	"\x0eGetPredecessor\x12\x1f.protogen.GetPredecessorRequest\x1a .protogen.GetPredecessorResponse\x12;\n" +
	"\x06Notify\x12\x17.protogen.NotifyRequest\x1a\x18.protogen.NotifyResponse\x12w\n" +
	"\x10GetSuccessorList\x12!.protogen.GetSuccessorListRequest\x1a\".protogen.GetSuccessorListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/node/successors\x12M\n" +
	"\x04Ping\x12\x15.protogen.PingRequest\x1a\x16.protogen.PingResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/node/ping\x12b\n" +
	"\vGetNodeInfo\x12\x1c.protogen.GetNodeInfoRequest\x1a\x1d.protogen.GetNodeInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/node/info\x12k\n" +
	"\x16ClosestPrecedingFinger\x12'.protogen.ClosestPrecedingFingerRequest\x1a(.protogen.ClosestPrecedingFingerResponse\x12M\n" +
	"\fTransferKeys\x12\x1d.protogen.TransferKeysRequest\x1a\x1e.protogen.TransferKeysResponse\x12h\n" +
	"\x15DeleteTransferredKeys\x12&.protogen.DeleteTransferredKeysRequest\x1a'.protogen.DeleteTransferredKeysResponse\x12K\n" +
	"\x03Get\x12\x14.protogen.GetRequest\x1a\x15.protogen.GetResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/keys/{key}\x12H\n" +
	"\x03Set\x12\x14.protogen.SetRequest\x1a\x15.protogen.SetResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/keys\x12T\n" +
	"\x06Delete\x12\x17.protogen.DeleteRequest\x1a\x18.protogen.DeleteResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/keys/{key}B*Z(github.com/zde37/torus/protobuf/protogenb\x06proto3"

var (
	file_chord_proto_rawDescOnce sync.Once
	file_chord_proto_rawDescData []byte
)

func file_chord_proto_rawDescGZIP() []byte {
	file_chord_proto_rawDescOnce.Do(func() {
		file_chord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chord_proto_rawDesc), len(file_chord_proto_rawDesc)))
	})
	return file_chord_proto_rawDescData
}

var file_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_chord_proto_goTypes = []any{
	(*Node)(nil),                           // 0: protogen.Node
	(*FindSuccessorRequest)(nil),           // 1: protogen.FindSuccessorRequest
	(*FindSuccessorResponse)(nil),          // 2: protogen.FindSuccessorResponse
	(*GetPredecessorRequest)(nil),          // 3: protogen.GetPredecessorRequest
	(*GetPredecessorResponse)(nil),         // 4: protogen.GetPredecessorResponse
	(*NotifyRequest)(nil),                  // 5: protogen.NotifyRequest
	(*NotifyResponse)(nil),                 // 6: protogen.NotifyResponse
	(*GetSuccessorListRequest)(nil),        // 7: protogen.GetSuccessorListRequest
	(*GetSuccessorListResponse)(nil),       // 8: protogen.GetSuccessorListResponse
	(*PingRequest)(nil),                    // 9: protogen.PingRequest
	(*PingResponse)(nil),                   // 10: protogen.PingResponse
	(*GetNodeInfoRequest)(nil),             // 11: protogen.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),            // 12: protogen.GetNodeInfoResponse
	(*GetRequest)(nil),                     // 13: protogen.GetRequest
	(*GetResponse)(nil),                    // 14: protogen.GetResponse
	(*SetRequest)(nil),                     // 15: protogen.SetRequest
	(*SetResponse)(nil),                    // 16: protogen.SetResponse
	(*DeleteRequest)(nil),                  // 17: protogen.DeleteRequest
	(*DeleteResponse)(nil),                 // 18: protogen.DeleteResponse
	(*ClosestPrecedingFingerRequest)(nil),  // 19: protogen.ClosestPrecedingFingerRequest
	(*ClosestPrecedingFingerResponse)(nil), // 20: protogen.ClosestPrecedingFingerResponse
	(*TransferKeysRequest)(nil),            // 21: protogen.TransferKeysRequest
	(*KeyValuePair)(nil),                   // 22: protogen.KeyValuePair
	(*TransferKeysResponse)(nil),           // 23: protogen.TransferKeysResponse
	(*DeleteTransferredKeysRequest)(nil),   // 24: protogen.DeleteTransferredKeysRequest
	(*DeleteTransferredKeysResponse)(nil),  // 25: protogen.DeleteTransferredKeysResponse
}
var file_chord_proto_depIdxs = []int32{
	0,  // 0: protogen.FindSuccessorResponse.successor:type_name -> protogen.Node
	0,  // 1: protogen.GetPredecessorResponse.predecessor:type_name -> protogen.Node
	0,  // 2: protogen.NotifyRequest.node:type_name -> protogen.Node
	0,  // 3: protogen.GetSuccessorListResponse.successors:type_name -> protogen.Node
	0,  // 4: protogen.GetNodeInfoResponse.node:type_name -> protogen.Node
	0,  // 5: protogen.ClosestPrecedingFingerResponse.node:type_name -> protogen.Node
	22, // 6: protogen.TransferKeysResponse.keys:type_name -> protogen.KeyValuePair
	1,  // 7: protogen.ChordService.FindSuccessor:input_type -> protogen.FindSuccessorRequest
	3,  // 8: protogen.ChordService.GetPredecessor:input_type -> protogen.GetPredecessorRequest
	5,  // 9: protogen.ChordService.Notify:input_type -> protogen.NotifyRequest
	7,  // 10: protogen.ChordService.GetSuccessorList:input_type -> protogen.GetSuccessorListRequest
	9,  // 11: protogen.ChordService.Ping:input_type -> protogen.PingRequest
	11, // 12: protogen.ChordService.GetNodeInfo:input_type -> protogen.GetNodeInfoRequest
	19, // 13: protogen.ChordService.ClosestPrecedingFinger:input_type -> protogen.ClosestPrecedingFingerRequest
	21, // 14: protogen.ChordService.TransferKeys:input_type -> protogen.TransferKeysRequest
	24, // 15: protogen.ChordService.DeleteTransferredKeys:input_type -> protogen.DeleteTransferredKeysRequest
	13, // 16: protogen.ChordService.Get:input_type -> protogen.GetRequest
	15, // 17: protogen.ChordService.Set:input_type -> protogen.SetRequest
	17, // 18: protogen.ChordService.Delete:input_type -> protogen.DeleteRequest
	2,  // 19: protogen.ChordService.FindSuccessor:output_type -> protogen.FindSuccessorResponse
	4,  // 20: protogen.ChordService.GetPredecessor:output_type -> protogen.GetPredecessorResponse
	6,  // 21: protogen.ChordService.Notify:output_type -> protogen.NotifyResponse
	8,  // 22: protogen.ChordService.GetSuccessorList:output_type -> protogen.GetSuccessorListResponse
	10, // 23: protogen.ChordService.Ping:output_type -> protogen.PingResponse
	12, // 24: protogen.ChordService.GetNodeInfo:output_type -> protogen.GetNodeInfoResponse
	20, // 25: protogen.ChordService.ClosestPrecedingFinger:output_type -> protogen.ClosestPrecedingFingerResponse
	23, // 26: protogen.ChordService.TransferKeys:output_type -> protogen.TransferKeysResponse
	25, // 27: protogen.ChordService.DeleteTransferredKeys:output_type -> protogen.DeleteTransferredKeysResponse
	14, // 28: protogen.ChordService.Get:output_type -> protogen.GetResponse
	16, // 29: protogen.ChordService.Set:output_type -> protogen.SetResponse
	18, // 30: protogen.ChordService.Delete:output_type -> protogen.DeleteResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chord_proto_init() }
func file_chord_proto_init() {
	if File_chord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chord_proto_rawDesc), len(file_chord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chord_proto_goTypes,
		DependencyIndexes: file_chord_proto_depIdxs,
		MessageInfos:      file_chord_proto_msgTypes,
	}.Build()
	File_chord_proto = out.File
	file_chord_proto_goTypes = nil
	file_chord_proto_depIdxs = nil
}
