// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: chord.proto

package protogen

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node represents a node in the Chord ring.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node ID as a byte array (160 bits / 20 bytes)
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Network host (IP address or hostname)
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// Network port (gRPC)
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// HTTP API port
	HttpPort int32 `protobuf:"varint,4,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`
	// Number of primary user keys stored (excluding Chord metadata and replica keys)
	KeyCount int32 `protobuf:"varint,5,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"`
	// Number of replica keys stored on this node
	ReplicaCount  int32 `protobuf:"varint,6,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_chord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Node) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Node) GetHttpPort() int32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

func (x *Node) GetKeyCount() int32 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

func (x *Node) GetReplicaCount() int32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

// FindSuccessorRequest asks a node to find the successor of a given ID.
type FindSuccessorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID to find the successor for
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRequest) Reset() {
	*x = FindSuccessorRequest{}
	mi := &file_chord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRequest) ProtoMessage() {}

func (x *FindSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{1}
}

func (x *FindSuccessorRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// FindSuccessorResponse contains the successor node.
type FindSuccessorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The successor node
	Successor     *Node `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorResponse) Reset() {
	*x = FindSuccessorResponse{}
	mi := &file_chord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorResponse) ProtoMessage() {}

func (x *FindSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorResponse.ProtoReflect.Descriptor instead.
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{2}
}

func (x *FindSuccessorResponse) GetSuccessor() *Node {
	if x != nil {
		return x.Successor
	}
	return nil
}

// FindSuccessorWithPathRequest asks a node to find the successor with path tracking.
type FindSuccessorWithPathRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID to find the successor for
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorWithPathRequest) Reset() {
	*x = FindSuccessorWithPathRequest{}
	mi := &file_chord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorWithPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorWithPathRequest) ProtoMessage() {}

func (x *FindSuccessorWithPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorWithPathRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorWithPathRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{3}
}

func (x *FindSuccessorWithPathRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// FindSuccessorWithPathResponse contains the successor and path from this node onwards.
type FindSuccessorWithPathResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The successor node
	Successor *Node `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	// Path taken from this node onwards (includes this node)
	Path          []*Node `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorWithPathResponse) Reset() {
	*x = FindSuccessorWithPathResponse{}
	mi := &file_chord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorWithPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorWithPathResponse) ProtoMessage() {}

func (x *FindSuccessorWithPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorWithPathResponse.ProtoReflect.Descriptor instead.
func (*FindSuccessorWithPathResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{4}
}

func (x *FindSuccessorWithPathResponse) GetSuccessor() *Node {
	if x != nil {
		return x.Successor
	}
	return nil
}

func (x *FindSuccessorWithPathResponse) GetPath() []*Node {
	if x != nil {
		return x.Path
	}
	return nil
}

// GetPredecessorRequest asks a node for its predecessor.
type GetPredecessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorRequest) Reset() {
	*x = GetPredecessorRequest{}
	mi := &file_chord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorRequest) ProtoMessage() {}

func (x *GetPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorRequest.ProtoReflect.Descriptor instead.
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{5}
}

// GetPredecessorResponse contains the predecessor node.
type GetPredecessorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The predecessor node (may be nil if not set)
	Predecessor   *Node `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorResponse) Reset() {
	*x = GetPredecessorResponse{}
	mi := &file_chord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorResponse) ProtoMessage() {}

func (x *GetPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorResponse.ProtoReflect.Descriptor instead.
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{6}
}

func (x *GetPredecessorResponse) GetPredecessor() *Node {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

// NotifyRequest notifies a node that another node might be its predecessor.
type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node that might be the predecessor
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_chord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// NotifyResponse acknowledges the notification.
type NotifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_chord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetSuccessorListRequest asks a node for its successor list.
type GetSuccessorListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorListRequest) Reset() {
	*x = GetSuccessorListRequest{}
	mi := &file_chord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListRequest) ProtoMessage() {}

func (x *GetSuccessorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListRequest.ProtoReflect.Descriptor instead.
func (*GetSuccessorListRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{9}
}

// GetSuccessorListResponse contains the successor list.
type GetSuccessorListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of successor nodes
	Successors    []*Node `protobuf:"bytes,1,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorListResponse) Reset() {
	*x = GetSuccessorListResponse{}
	mi := &file_chord_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListResponse) ProtoMessage() {}

func (x *GetSuccessorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListResponse.ProtoReflect.Descriptor instead.
func (*GetSuccessorListResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{10}
}

func (x *GetSuccessorListResponse) GetSuccessors() []*Node {
	if x != nil {
		return x.Successors
	}
	return nil
}

// PingRequest is used for health checks.
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_chord_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{11}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PingResponse acknowledges the ping.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp of the response
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_chord_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{12}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetNodeInfoRequest asks for the node's information.
type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_chord_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{13}
}

// GetNodeInfoResponse contains the node's information.
type GetNodeInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's information
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_chord_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{14}
}

func (x *GetNodeInfoResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// GetRequest retrieves a value by key from the DHT.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to retrieve
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_chord_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{15}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse contains the retrieved value.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value (empty if not found)
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Whether the key was found
	Found         bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_chord_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{16}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// SetRequest stores a key-value pair in the DHT.
type SetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to store
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value to store
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// TTL in seconds (0 = no expiration)
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_chord_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{17}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// SetResponse acknowledges the set operation.
type SetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_chord_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{18}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeleteRequest removes a key from the DHT.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to delete
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_chord_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteResponse acknowledges the delete operation.
type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_chord_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SetReplicaRequest stores a replica of a key on a successor node.
type SetReplicaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to replicate
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value to replicate
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// TTL in seconds (0 = no expiration)
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReplicaRequest) Reset() {
	*x = SetReplicaRequest{}
	mi := &file_chord_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReplicaRequest) ProtoMessage() {}

func (x *SetReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReplicaRequest.ProtoReflect.Descriptor instead.
func (*SetReplicaRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{21}
}

func (x *SetReplicaRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReplicaRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetReplicaRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// SetReplicaResponse acknowledges the replica storage.
type SetReplicaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReplicaResponse) Reset() {
	*x = SetReplicaResponse{}
	mi := &file_chord_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReplicaResponse) ProtoMessage() {}

func (x *SetReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReplicaResponse.ProtoReflect.Descriptor instead.
func (*SetReplicaResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{22}
}

func (x *SetReplicaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetReplicaRequest retrieves a replica of a key.
type GetReplicaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to retrieve
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaRequest) Reset() {
	*x = GetReplicaRequest{}
	mi := &file_chord_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaRequest) ProtoMessage() {}

func (x *GetReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaRequest.ProtoReflect.Descriptor instead.
func (*GetReplicaRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{23}
}

func (x *GetReplicaRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetReplicaResponse contains the replica value.
type GetReplicaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value (empty if not found)
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Whether the replica was found
	Found         bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaResponse) Reset() {
	*x = GetReplicaResponse{}
	mi := &file_chord_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaResponse) ProtoMessage() {}

func (x *GetReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaResponse.ProtoReflect.Descriptor instead.
func (*GetReplicaResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{24}
}

func (x *GetReplicaResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetReplicaResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// DeleteReplicaRequest removes a replica of a key.
type DeleteReplicaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to delete
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplicaRequest) Reset() {
	*x = DeleteReplicaRequest{}
	mi := &file_chord_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplicaRequest) ProtoMessage() {}

func (x *DeleteReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplicaRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplicaRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteReplicaRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteReplicaResponse acknowledges the replica deletion.
type DeleteReplicaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplicaResponse) Reset() {
	*x = DeleteReplicaResponse{}
	mi := &file_chord_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplicaResponse) ProtoMessage() {}

func (x *DeleteReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplicaResponse.ProtoReflect.Descriptor instead.
func (*DeleteReplicaResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteReplicaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ClosestPrecedingFingerRequest asks for the closest preceding finger.
type ClosestPrecedingFingerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID to find the closest preceding finger for
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosestPrecedingFingerRequest) Reset() {
	*x = ClosestPrecedingFingerRequest{}
	mi := &file_chord_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosestPrecedingFingerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosestPrecedingFingerRequest) ProtoMessage() {}

func (x *ClosestPrecedingFingerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosestPrecedingFingerRequest.ProtoReflect.Descriptor instead.
func (*ClosestPrecedingFingerRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{27}
}

func (x *ClosestPrecedingFingerRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// ClosestPrecedingFingerResponse contains the closest preceding node.
type ClosestPrecedingFingerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The closest preceding node
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosestPrecedingFingerResponse) Reset() {
	*x = ClosestPrecedingFingerResponse{}
	mi := &file_chord_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosestPrecedingFingerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosestPrecedingFingerResponse) ProtoMessage() {}

func (x *ClosestPrecedingFingerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosestPrecedingFingerResponse.ProtoReflect.Descriptor instead.
func (*ClosestPrecedingFingerResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{28}
}

func (x *ClosestPrecedingFingerResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// TransferKeysRequest asks a node to transfer keys in a range.
type TransferKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the range (exclusive)
	StartId []byte `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	// End of the range (inclusive)
	EndId         []byte `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferKeysRequest) Reset() {
	*x = TransferKeysRequest{}
	mi := &file_chord_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferKeysRequest) ProtoMessage() {}

func (x *TransferKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferKeysRequest.ProtoReflect.Descriptor instead.
func (*TransferKeysRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{29}
}

func (x *TransferKeysRequest) GetStartId() []byte {
	if x != nil {
		return x.StartId
	}
	return nil
}

func (x *TransferKeysRequest) GetEndId() []byte {
	if x != nil {
		return x.EndId
	}
	return nil
}

// KeyValuePair represents a single key-value pair.
type KeyValuePair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// TTL remaining in seconds (0 = no expiration)
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_chord_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{30}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValuePair) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// TransferKeysResponse contains the keys in the requested range.
type TransferKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of key-value pairs
	Keys []*KeyValuePair `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Number of keys transferred
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferKeysResponse) Reset() {
	*x = TransferKeysResponse{}
	mi := &file_chord_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferKeysResponse) ProtoMessage() {}

func (x *TransferKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferKeysResponse.ProtoReflect.Descriptor instead.
func (*TransferKeysResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{31}
}

func (x *TransferKeysResponse) GetKeys() []*KeyValuePair {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TransferKeysResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// DeleteTransferredKeysRequest asks a node to delete keys in a range.
type DeleteTransferredKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the range (exclusive)
	StartId []byte `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	// End of the range (inclusive)
	EndId         []byte `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferredKeysRequest) Reset() {
	*x = DeleteTransferredKeysRequest{}
	mi := &file_chord_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferredKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferredKeysRequest) ProtoMessage() {}

func (x *DeleteTransferredKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferredKeysRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransferredKeysRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteTransferredKeysRequest) GetStartId() []byte {
	if x != nil {
		return x.StartId
	}
	return nil
}

func (x *DeleteTransferredKeysRequest) GetEndId() []byte {
	if x != nil {
		return x.EndId
	}
	return nil
}

// DeleteTransferredKeysResponse confirms deletion.
type DeleteTransferredKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether deletion was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of keys deleted
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferredKeysResponse) Reset() {
	*x = DeleteTransferredKeysResponse{}
	mi := &file_chord_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferredKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferredKeysResponse) ProtoMessage() {}

func (x *DeleteTransferredKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferredKeysResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransferredKeysResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteTransferredKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTransferredKeysResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// LookupPathRequest asks a node to find a key and return the path taken.
type LookupPathRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to lookup
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupPathRequest) Reset() {
	*x = LookupPathRequest{}
	mi := &file_chord_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPathRequest) ProtoMessage() {}

func (x *LookupPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPathRequest.ProtoReflect.Descriptor instead.
func (*LookupPathRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{34}
}

func (x *LookupPathRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// LookupPathResponse contains the lookup result and path taken.
type LookupPathResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key that was looked up
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Hash of the key
	KeyHash []byte `protobuf:"bytes,2,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	// The node responsible for this key
	ResponsibleNode *Node `protobuf:"bytes,3,opt,name=responsible_node,json=responsibleNode,proto3" json:"responsible_node,omitempty"`
	// List of nodes visited during the lookup (in order)
	Path []*Node `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
	// Number of hops taken
	Hops          int32 `protobuf:"varint,5,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupPathResponse) Reset() {
	*x = LookupPathResponse{}
	mi := &file_chord_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPathResponse) ProtoMessage() {}

func (x *LookupPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPathResponse.ProtoReflect.Descriptor instead.
func (*LookupPathResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{35}
}

func (x *LookupPathResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LookupPathResponse) GetKeyHash() []byte {
	if x != nil {
		return x.KeyHash
	}
	return nil
}

func (x *LookupPathResponse) GetResponsibleNode() *Node {
	if x != nil {
		return x.ResponsibleNode
	}
	return nil
}

func (x *LookupPathResponse) GetPath() []*Node {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *LookupPathResponse) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

// GetFingerTableRequest asks a node for its finger table.
type GetFingerTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFingerTableRequest) Reset() {
	*x = GetFingerTableRequest{}
	mi := &file_chord_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFingerTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFingerTableRequest) ProtoMessage() {}

func (x *GetFingerTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFingerTableRequest.ProtoReflect.Descriptor instead.
func (*GetFingerTableRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{36}
}

// FingerTableEntry represents a single entry in the finger table.
type FingerTableEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the interval: (n + 2^(i-1)) mod 2^M
	Start []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// The node that succeeds or equals start
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Index in the finger table (0 to M-1)
	Index         int32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FingerTableEntry) Reset() {
	*x = FingerTableEntry{}
	mi := &file_chord_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerTableEntry) ProtoMessage() {}

func (x *FingerTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerTableEntry.ProtoReflect.Descriptor instead.
func (*FingerTableEntry) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{37}
}

func (x *FingerTableEntry) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *FingerTableEntry) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *FingerTableEntry) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// GetFingerTableResponse contains the node's finger table.
type GetFingerTableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of finger table entries
	Entries       []*FingerTableEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFingerTableResponse) Reset() {
	*x = GetFingerTableResponse{}
	mi := &file_chord_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFingerTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFingerTableResponse) ProtoMessage() {}

func (x *GetFingerTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFingerTableResponse.ProtoReflect.Descriptor instead.
func (*GetFingerTableResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{38}
}

func (x *GetFingerTableResponse) GetEntries() []*FingerTableEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// BulkStoreRequest contains multiple key-value pairs to store.
type BulkStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of keys to values
	Items         map[string][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkStoreRequest) Reset() {
	*x = BulkStoreRequest{}
	mi := &file_chord_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStoreRequest) ProtoMessage() {}

func (x *BulkStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkStoreRequest.ProtoReflect.Descriptor instead.
func (*BulkStoreRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{39}
}

func (x *BulkStoreRequest) GetItems() map[string][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

// BulkStoreResponse confirms bulk storage.
type BulkStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of items stored
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Optional error message for failed items
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkStoreResponse) Reset() {
	*x = BulkStoreResponse{}
	mi := &file_chord_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStoreResponse) ProtoMessage() {}

func (x *BulkStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkStoreResponse.ProtoReflect.Descriptor instead.
func (*BulkStoreResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{40}
}

func (x *BulkStoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkStoreResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BulkStoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// NotifyPredecessorLeavingRequest notifies predecessor about node leaving.
type NotifyPredecessorLeavingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new successor after the leaving node
	NewSuccessor  *Node `protobuf:"bytes,1,opt,name=new_successor,json=newSuccessor,proto3" json:"new_successor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPredecessorLeavingRequest) Reset() {
	*x = NotifyPredecessorLeavingRequest{}
	mi := &file_chord_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPredecessorLeavingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPredecessorLeavingRequest) ProtoMessage() {}

func (x *NotifyPredecessorLeavingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPredecessorLeavingRequest.ProtoReflect.Descriptor instead.
func (*NotifyPredecessorLeavingRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{41}
}

func (x *NotifyPredecessorLeavingRequest) GetNewSuccessor() *Node {
	if x != nil {
		return x.NewSuccessor
	}
	return nil
}

// NotifyPredecessorLeavingResponse acknowledges the notification.
type NotifyPredecessorLeavingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the notification was processed successfully
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPredecessorLeavingResponse) Reset() {
	*x = NotifyPredecessorLeavingResponse{}
	mi := &file_chord_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPredecessorLeavingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPredecessorLeavingResponse) ProtoMessage() {}

func (x *NotifyPredecessorLeavingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPredecessorLeavingResponse.ProtoReflect.Descriptor instead.
func (*NotifyPredecessorLeavingResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{42}
}

func (x *NotifyPredecessorLeavingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// NotifySuccessorLeavingRequest notifies successor about node leaving.
type NotifySuccessorLeavingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new predecessor after the leaving node
	NewPredecessor *Node `protobuf:"bytes,1,opt,name=new_predecessor,json=newPredecessor,proto3" json:"new_predecessor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifySuccessorLeavingRequest) Reset() {
	*x = NotifySuccessorLeavingRequest{}
	mi := &file_chord_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifySuccessorLeavingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifySuccessorLeavingRequest) ProtoMessage() {}

func (x *NotifySuccessorLeavingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifySuccessorLeavingRequest.ProtoReflect.Descriptor instead.
func (*NotifySuccessorLeavingRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{43}
}

func (x *NotifySuccessorLeavingRequest) GetNewPredecessor() *Node {
	if x != nil {
		return x.NewPredecessor
	}
	return nil
}

// NotifySuccessorLeavingResponse acknowledges the notification.
type NotifySuccessorLeavingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the notification was processed successfully
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifySuccessorLeavingResponse) Reset() {
	*x = NotifySuccessorLeavingResponse{}
	mi := &file_chord_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifySuccessorLeavingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifySuccessorLeavingResponse) ProtoMessage() {}

func (x *NotifySuccessorLeavingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifySuccessorLeavingResponse.ProtoReflect.Descriptor instead.
func (*NotifySuccessorLeavingResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{44}
}

func (x *NotifySuccessorLeavingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// NotifyNodeLeavingRequest notifies a node about another node leaving.
type NotifyNodeLeavingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node that is leaving
	LeavingNode   *Node `protobuf:"bytes,1,opt,name=leaving_node,json=leavingNode,proto3" json:"leaving_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeLeavingRequest) Reset() {
	*x = NotifyNodeLeavingRequest{}
	mi := &file_chord_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeLeavingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeLeavingRequest) ProtoMessage() {}

func (x *NotifyNodeLeavingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeLeavingRequest.ProtoReflect.Descriptor instead.
func (*NotifyNodeLeavingRequest) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{45}
}

func (x *NotifyNodeLeavingRequest) GetLeavingNode() *Node {
	if x != nil {
		return x.LeavingNode
	}
	return nil
}

// NotifyNodeLeavingResponse acknowledges the notification.
type NotifyNodeLeavingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the notification was processed successfully
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeLeavingResponse) Reset() {
	*x = NotifyNodeLeavingResponse{}
	mi := &file_chord_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeLeavingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeLeavingResponse) ProtoMessage() {}

func (x *NotifyNodeLeavingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chord_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeLeavingResponse.ProtoReflect.Descriptor instead.
func (*NotifyNodeLeavingResponse) Descriptor() ([]byte, []int) {
	return file_chord_proto_rawDescGZIP(), []int{46}
}

func (x *NotifyNodeLeavingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_chord_proto protoreflect.FileDescriptor

const file_chord_proto_rawDesc = "" +
	"\n" +
	"\vchord.proto\x12\bprotogen\x1a\x1cgoogle/api/annotations.proto\"\x9d\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1b\n" +
	"\thttp_port\x18\x04 \x01(\x05R\bhttpPort\x12\x1b\n" +
	"\tkey_count\x18\x05 \x01(\x05R\bkeyCount\x12#\n" +
	"\rreplica_count\x18\x06 \x01(\x05R\freplicaCount\"&\n" +
	"\x14FindSuccessorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"E\n" +
	"\x15FindSuccessorResponse\x12,\n" +
	"\tsuccessor\x18\x01 \x01(\v2\x0e.protogen.NodeR\tsuccessor\".\n" +
	"\x1cFindSuccessorWithPathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"q\n" +
	"\x1dFindSuccessorWithPathResponse\x12,\n" +
	"\tsuccessor\x18\x01 \x01(\v2\x0e.protogen.NodeR\tsuccessor\x12\"\n" +
	"\x04path\x18\x02 \x03(\v2\x0e.protogen.NodeR\x04path\"\x17\n" +
	"\x15GetPredecessorRequest\"J\n" +
	"\x16GetPredecessorResponse\x120\n" +
	"\vpredecessor\x18\x01 \x01(\v2\x0e.protogen.NodeR\vpredecessor\"3\n" +
	"\rNotifyRequest\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.protogen.NodeR\x04node\"*\n" +
	"\x0eNotifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x19\n" +
	"\x17GetSuccessorListRequest\"J\n" +
	"\x18GetSuccessorListResponse\x12.\n" +
	"\n" +
	"successors\x18\x01 \x03(\v2\x0e.protogen.NodeR\n" +
	"successors\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x14\n" +
	"\x12GetNodeInfoRequest\"9\n" +
	"\x13GetNodeInfoResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.protogen.NodeR\x04node\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"U\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x11SetReplicaRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\".\n" +
	"\x12SetReplicaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x11GetReplicaRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"@\n" +
	"\x12GetReplicaResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"(\n" +
	"\x14DeleteReplicaRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"1\n" +
	"\x15DeleteReplicaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x1dClosestPrecedingFingerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"D\n" +
	"\x1eClosestPrecedingFingerResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.protogen.NodeR\x04node\"G\n" +
	"\x13TransferKeysRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\fR\astartId\x12\x15\n" +
	"\x06end_id\x18\x02 \x01(\fR\x05endId\"W\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"X\n" +
	"\x14TransferKeysResponse\x12*\n" +
	"\x04keys\x18\x01 \x03(\v2\x16.protogen.KeyValuePairR\x04keys\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"P\n" +
	"\x1cDeleteTransferredKeysRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\fR\astartId\x12\x15\n" +
	"\x06end_id\x18\x02 \x01(\fR\x05endId\"O\n" +
	"\x1dDeleteTransferredKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"%\n" +
	"\x11LookupPathRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xb4\x01\n" +
	"\x12LookupPathResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\bkey_hash\x18\x02 \x01(\fR\akeyHash\x129\n" +
	"\x10responsible_node\x18\x03 \x01(\v2\x0e.protogen.NodeR\x0fresponsibleNode\x12\"\n" +
	"\x04path\x18\x04 \x03(\v2\x0e.protogen.NodeR\x04path\x12\x12\n" +
	"\x04hops\x18\x05 \x01(\x05R\x04hops\"\x17\n" +
	"\x15GetFingerTableRequest\"b\n" +
	"\x10FingerTableEntry\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\"\n" +
	"\x04node\x18\x02 \x01(\v2\x0e.protogen.NodeR\x04node\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"N\n" +
	"\x16GetFingerTableResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.protogen.FingerTableEntryR\aentries\"\x89\x01\n" +
	"\x10BulkStoreRequest\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.protogen.BulkStoreRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"Y\n" +
	"\x11BulkStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"V\n" +
	"\x1fNotifyPredecessorLeavingRequest\x123\n" +
	"\rnew_successor\x18\x01 \x01(\v2\x0e.protogen.NodeR\fnewSuccessor\"<\n" +
	" NotifyPredecessorLeavingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"X\n" +
	"\x1dNotifySuccessorLeavingRequest\x127\n" +
	"\x0fnew_predecessor\x18\x01 \x01(\v2\x0e.protogen.NodeR\x0enewPredecessor\":\n" +
	"\x1eNotifySuccessorLeavingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x18NotifyNodeLeavingRequest\x121\n" +
	"\fleaving_node\x18\x01 \x01(\v2\x0e.protogen.NodeR\vleavingNode\"5\n" +
	"\x19NotifyNodeLeavingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf6\x0f\n" +
	"\fChordService\x12P\n" +
	"\rFindSuccessor\x12\x1e.protogen.FindSuccessorRequest\x1a\x1f.protogen.FindSuccessorResponse\x12h\n" +
	"\x15FindSuccessorWithPath\x12&.protogen.FindSuccessorWithPathRequest\x1a'.protogen.FindSuccessorWithPathResponse\x12r\n" +
	"\x0eGetPredecessor\x12\x1f.protogen.GetPredecessorRequest\x1a .protogen.GetPredecessorResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/node/predecessor\x12;\n" +
	"\x06Notify\x12\x17.protogen.NotifyRequest\x1a\x18.protogen.NotifyResponse\x12w\n" +
	"\x10GetSuccessorList\x12!.protogen.GetSuccessorListRequest\x1a\".protogen.GetSuccessorListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/node/successors\x12M\n" +
	"\x04Ping\x12\x15.protogen.PingRequest\x1a\x16.protogen.PingResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/node/ping\x12b\n" +
	"\vGetNodeInfo\x12\x1c.protogen.GetNodeInfoRequest\x1a\x1d.protogen.GetNodeInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/node/info\x12k\n" +
	"\x16ClosestPrecedingFinger\x12'.protogen.ClosestPrecedingFingerRequest\x1a(.protogen.ClosestPrecedingFingerResponse\x12M\n" +
	"\fTransferKeys\x12\x1d.protogen.TransferKeysRequest\x1a\x1e.protogen.TransferKeysResponse\x12h\n" +
	"\x15DeleteTransferredKeys\x12&.protogen.DeleteTransferredKeysRequest\x1a'.protogen.DeleteTransferredKeysResponse\x12K\n" +
	"\x03Get\x12\x14.protogen.GetRequest\x1a\x15.protogen.GetResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/keys/{key}\x12H\n" +
	"\x03Set\x12\x14.protogen.SetRequest\x1a\x15.protogen.SetResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/keys\x12T\n" +
	"\x06Delete\x12\x17.protogen.DeleteRequest\x1a\x18.protogen.DeleteResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/keys/{key}\x12b\n" +
	"\n" +
	"LookupPath\x12\x1b.protogen.LookupPathRequest\x1a\x1c.protogen.LookupPathResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/lookup/{key}\x12n\n" +
	"\x0eGetFingerTable\x12\x1f.protogen.GetFingerTableRequest\x1a .protogen.GetFingerTableResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/node/fingers\x12G\n" +
	"\n" +
	"SetReplica\x12\x1b.protogen.SetReplicaRequest\x1a\x1c.protogen.SetReplicaResponse\x12G\n" +
	"\n" +
	"GetReplica\x12\x1b.protogen.GetReplicaRequest\x1a\x1c.protogen.GetReplicaResponse\x12P\n" +
	"\rDeleteReplica\x12\x1e.protogen.DeleteReplicaRequest\x1a\x1f.protogen.DeleteReplicaResponse\x12D\n" +
	"\tBulkStore\x12\x1a.protogen.BulkStoreRequest\x1a\x1b.protogen.BulkStoreResponse\x12q\n" +
	"\x18NotifyPredecessorLeaving\x12).protogen.NotifyPredecessorLeavingRequest\x1a*.protogen.NotifyPredecessorLeavingResponse\x12k\n" +
	"\x16NotifySuccessorLeaving\x12'.protogen.NotifySuccessorLeavingRequest\x1a(.protogen.NotifySuccessorLeavingResponse\x12\\\n" +
	"\x11NotifyNodeLeaving\x12\".protogen.NotifyNodeLeavingRequest\x1a#.protogen.NotifyNodeLeavingResponseB*Z(github.com/zde37/torus/protobuf/protogenb\x06proto3"

var (
	file_chord_proto_rawDescOnce sync.Once
	file_chord_proto_rawDescData []byte
)

func file_chord_proto_rawDescGZIP() []byte {
	file_chord_proto_rawDescOnce.Do(func() {
		file_chord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chord_proto_rawDesc), len(file_chord_proto_rawDesc)))
	})
	return file_chord_proto_rawDescData
}

var file_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_chord_proto_goTypes = []any{
	(*Node)(nil),                             // 0: protogen.Node
	(*FindSuccessorRequest)(nil),             // 1: protogen.FindSuccessorRequest
	(*FindSuccessorResponse)(nil),            // 2: protogen.FindSuccessorResponse
	(*FindSuccessorWithPathRequest)(nil),     // 3: protogen.FindSuccessorWithPathRequest
	(*FindSuccessorWithPathResponse)(nil),    // 4: protogen.FindSuccessorWithPathResponse
	(*GetPredecessorRequest)(nil),            // 5: protogen.GetPredecessorRequest
	(*GetPredecessorResponse)(nil),           // 6: protogen.GetPredecessorResponse
	(*NotifyRequest)(nil),                    // 7: protogen.NotifyRequest
	(*NotifyResponse)(nil),                   // 8: protogen.NotifyResponse
	(*GetSuccessorListRequest)(nil),          // 9: protogen.GetSuccessorListRequest
	(*GetSuccessorListResponse)(nil),         // 10: protogen.GetSuccessorListResponse
	(*PingRequest)(nil),                      // 11: protogen.PingRequest
	(*PingResponse)(nil),                     // 12: protogen.PingResponse
	(*GetNodeInfoRequest)(nil),               // 13: protogen.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),              // 14: protogen.GetNodeInfoResponse
	(*GetRequest)(nil),                       // 15: protogen.GetRequest
	(*GetResponse)(nil),                      // 16: protogen.GetResponse
	(*SetRequest)(nil),                       // 17: protogen.SetRequest
	(*SetResponse)(nil),                      // 18: protogen.SetResponse
	(*DeleteRequest)(nil),                    // 19: protogen.DeleteRequest
	(*DeleteResponse)(nil),                   // 20: protogen.DeleteResponse
	(*SetReplicaRequest)(nil),                // 21: protogen.SetReplicaRequest
	(*SetReplicaResponse)(nil),               // 22: protogen.SetReplicaResponse
	(*GetReplicaRequest)(nil),                // 23: protogen.GetReplicaRequest
	(*GetReplicaResponse)(nil),               // 24: protogen.GetReplicaResponse
	(*DeleteReplicaRequest)(nil),             // 25: protogen.DeleteReplicaRequest
	(*DeleteReplicaResponse)(nil),            // 26: protogen.DeleteReplicaResponse
	(*ClosestPrecedingFingerRequest)(nil),    // 27: protogen.ClosestPrecedingFingerRequest
	(*ClosestPrecedingFingerResponse)(nil),   // 28: protogen.ClosestPrecedingFingerResponse
	(*TransferKeysRequest)(nil),              // 29: protogen.TransferKeysRequest
	(*KeyValuePair)(nil),                     // 30: protogen.KeyValuePair
	(*TransferKeysResponse)(nil),             // 31: protogen.TransferKeysResponse
	(*DeleteTransferredKeysRequest)(nil),     // 32: protogen.DeleteTransferredKeysRequest
	(*DeleteTransferredKeysResponse)(nil),    // 33: protogen.DeleteTransferredKeysResponse
	(*LookupPathRequest)(nil),                // 34: protogen.LookupPathRequest
	(*LookupPathResponse)(nil),               // 35: protogen.LookupPathResponse
	(*GetFingerTableRequest)(nil),            // 36: protogen.GetFingerTableRequest
	(*FingerTableEntry)(nil),                 // 37: protogen.FingerTableEntry
	(*GetFingerTableResponse)(nil),           // 38: protogen.GetFingerTableResponse
	(*BulkStoreRequest)(nil),                 // 39: protogen.BulkStoreRequest
	(*BulkStoreResponse)(nil),                // 40: protogen.BulkStoreResponse
	(*NotifyPredecessorLeavingRequest)(nil),  // 41: protogen.NotifyPredecessorLeavingRequest
	(*NotifyPredecessorLeavingResponse)(nil), // 42: protogen.NotifyPredecessorLeavingResponse
	(*NotifySuccessorLeavingRequest)(nil),    // 43: protogen.NotifySuccessorLeavingRequest
	(*NotifySuccessorLeavingResponse)(nil),   // 44: protogen.NotifySuccessorLeavingResponse
	(*NotifyNodeLeavingRequest)(nil),         // 45: protogen.NotifyNodeLeavingRequest
	(*NotifyNodeLeavingResponse)(nil),        // 46: protogen.NotifyNodeLeavingResponse
	nil,                                      // 47: protogen.BulkStoreRequest.ItemsEntry
}
var file_chord_proto_depIdxs = []int32{
	0,  // 0: protogen.FindSuccessorResponse.successor:type_name -> protogen.Node
	0,  // 1: protogen.FindSuccessorWithPathResponse.successor:type_name -> protogen.Node
	0,  // 2: protogen.FindSuccessorWithPathResponse.path:type_name -> protogen.Node
	0,  // 3: protogen.GetPredecessorResponse.predecessor:type_name -> protogen.Node
	0,  // 4: protogen.NotifyRequest.node:type_name -> protogen.Node
	0,  // 5: protogen.GetSuccessorListResponse.successors:type_name -> protogen.Node
	0,  // 6: protogen.GetNodeInfoResponse.node:type_name -> protogen.Node
	0,  // 7: protogen.ClosestPrecedingFingerResponse.node:type_name -> protogen.Node
	30, // 8: protogen.TransferKeysResponse.keys:type_name -> protogen.KeyValuePair
	0,  // 9: protogen.LookupPathResponse.responsible_node:type_name -> protogen.Node
	0,  // 10: protogen.LookupPathResponse.path:type_name -> protogen.Node
	0,  // 11: protogen.FingerTableEntry.node:type_name -> protogen.Node
	37, // 12: protogen.GetFingerTableResponse.entries:type_name -> protogen.FingerTableEntry
	47, // 13: protogen.BulkStoreRequest.items:type_name -> protogen.BulkStoreRequest.ItemsEntry
	0,  // 14: protogen.NotifyPredecessorLeavingRequest.new_successor:type_name -> protogen.Node
	0,  // 15: protogen.NotifySuccessorLeavingRequest.new_predecessor:type_name -> protogen.Node
	0,  // 16: protogen.NotifyNodeLeavingRequest.leaving_node:type_name -> protogen.Node
	1,  // 17: protogen.ChordService.FindSuccessor:input_type -> protogen.FindSuccessorRequest
	3,  // 18: protogen.ChordService.FindSuccessorWithPath:input_type -> protogen.FindSuccessorWithPathRequest
	5,  // 19: protogen.ChordService.GetPredecessor:input_type -> protogen.GetPredecessorRequest
	7,  // 20: protogen.ChordService.Notify:input_type -> protogen.NotifyRequest
	9,  // 21: protogen.ChordService.GetSuccessorList:input_type -> protogen.GetSuccessorListRequest
	11, // 22: protogen.ChordService.Ping:input_type -> protogen.PingRequest
	13, // 23: protogen.ChordService.GetNodeInfo:input_type -> protogen.GetNodeInfoRequest
	27, // 24: protogen.ChordService.ClosestPrecedingFinger:input_type -> protogen.ClosestPrecedingFingerRequest
	29, // 25: protogen.ChordService.TransferKeys:input_type -> protogen.TransferKeysRequest
	32, // 26: protogen.ChordService.DeleteTransferredKeys:input_type -> protogen.DeleteTransferredKeysRequest
	15, // 27: protogen.ChordService.Get:input_type -> protogen.GetRequest
	17, // 28: protogen.ChordService.Set:input_type -> protogen.SetRequest
	19, // 29: protogen.ChordService.Delete:input_type -> protogen.DeleteRequest
	34, // 30: protogen.ChordService.LookupPath:input_type -> protogen.LookupPathRequest
	36, // 31: protogen.ChordService.GetFingerTable:input_type -> protogen.GetFingerTableRequest
	21, // 32: protogen.ChordService.SetReplica:input_type -> protogen.SetReplicaRequest
	23, // 33: protogen.ChordService.GetReplica:input_type -> protogen.GetReplicaRequest
	25, // 34: protogen.ChordService.DeleteReplica:input_type -> protogen.DeleteReplicaRequest
	39, // 35: protogen.ChordService.BulkStore:input_type -> protogen.BulkStoreRequest
	41, // 36: protogen.ChordService.NotifyPredecessorLeaving:input_type -> protogen.NotifyPredecessorLeavingRequest
	43, // 37: protogen.ChordService.NotifySuccessorLeaving:input_type -> protogen.NotifySuccessorLeavingRequest
	45, // 38: protogen.ChordService.NotifyNodeLeaving:input_type -> protogen.NotifyNodeLeavingRequest
	2,  // 39: protogen.ChordService.FindSuccessor:output_type -> protogen.FindSuccessorResponse
	4,  // 40: protogen.ChordService.FindSuccessorWithPath:output_type -> protogen.FindSuccessorWithPathResponse
	6,  // 41: protogen.ChordService.GetPredecessor:output_type -> protogen.GetPredecessorResponse
	8,  // 42: protogen.ChordService.Notify:output_type -> protogen.NotifyResponse
	10, // 43: protogen.ChordService.GetSuccessorList:output_type -> protogen.GetSuccessorListResponse
	12, // 44: protogen.ChordService.Ping:output_type -> protogen.PingResponse
	14, // 45: protogen.ChordService.GetNodeInfo:output_type -> protogen.GetNodeInfoResponse
	28, // 46: protogen.ChordService.ClosestPrecedingFinger:output_type -> protogen.ClosestPrecedingFingerResponse
	31, // 47: protogen.ChordService.TransferKeys:output_type -> protogen.TransferKeysResponse
	33, // 48: protogen.ChordService.DeleteTransferredKeys:output_type -> protogen.DeleteTransferredKeysResponse
	16, // 49: protogen.ChordService.Get:output_type -> protogen.GetResponse
	18, // 50: protogen.ChordService.Set:output_type -> protogen.SetResponse
	20, // 51: protogen.ChordService.Delete:output_type -> protogen.DeleteResponse
	35, // 52: protogen.ChordService.LookupPath:output_type -> protogen.LookupPathResponse
	38, // 53: protogen.ChordService.GetFingerTable:output_type -> protogen.GetFingerTableResponse
	22, // 54: protogen.ChordService.SetReplica:output_type -> protogen.SetReplicaResponse
	24, // 55: protogen.ChordService.GetReplica:output_type -> protogen.GetReplicaResponse
	26, // 56: protogen.ChordService.DeleteReplica:output_type -> protogen.DeleteReplicaResponse
	40, // 57: protogen.ChordService.BulkStore:output_type -> protogen.BulkStoreResponse
	42, // 58: protogen.ChordService.NotifyPredecessorLeaving:output_type -> protogen.NotifyPredecessorLeavingResponse
	44, // 59: protogen.ChordService.NotifySuccessorLeaving:output_type -> protogen.NotifySuccessorLeavingResponse
	46, // 60: protogen.ChordService.NotifyNodeLeaving:output_type -> protogen.NotifyNodeLeavingResponse
	39, // [39:61] is the sub-list for method output_type
	17, // [17:39] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_chord_proto_init() }
func file_chord_proto_init() {
	if File_chord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chord_proto_rawDesc), len(file_chord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chord_proto_goTypes,
		DependencyIndexes: file_chord_proto_depIdxs,
		MessageInfos:      file_chord_proto_msgTypes,
	}.Build()
	File_chord_proto = out.File
	file_chord_proto_goTypes = nil
	file_chord_proto_depIdxs = nil
}
